version: '3.5'

services:
  cache:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
  server:
    build:
      context: .
    command: yarn dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 9001:9001
    depends_on:
      - cache
      - mongo
