version: '3.5'

services:
  cache:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - ./config/mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: 'howiwish'
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
  server:
    build:
      context: .
    command: yarn dev
    environment:
      MONGO_URL: 'mongodb://mongo:27017/'
      MONGO_DB: 'howiwish'
    volumes:
      - ./:/usr/src/app
    ports:
      - 9001:4000
    depends_on:
      - cache
      - mongo
